[versions]
springframework-boot = "3.2.2"
spring-dependency-management = "1.1.4"
jsonwebtoken = "0.12.3"

[libraries]
springboot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
springboot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
springboot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
postgresql = { module = "org.postgresql:postgresql" }
lombok = { module = "org.projectlombok:lombok" }
jsonwebtoken-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jsonwebtoken" }
jsonwebtoken-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jsonwebtoken" }
jsonwebtoken-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jsonwebtoken" }
springboot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
springboot-security-test = { module = "org.springframework.security:spring-security-test" }

[plugins]
springframework-boot = { id = "org.springframework.boot", version.ref = "springframework-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
